//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        public int ID { get; set; }
        public string TenCuaHang { get; set; }
        public string DiaChi { get; set; }
        public double DoanhThu { get; set; }
        public int SoKhach { get; set; }
        public int ChuoiCuaHang { get; set; }
        public int isDeleted { get; set; }
    }
}
